### PR TITLE
Remove SPNCreation Script

### PR DESCRIPTION
**Pull request by asranja**

### CODE REVIEW

**Comment by asranja** [comment]
The script is moved here https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskModules/powershell/Azure/SPNCreation.ps1.

**Review by kmkumaran — APPROVED** [review]

**Review by alexhomer1 — APPROVED** [review]

**Comment by gholliday** [comment]
@asranja @kmkumaran can you merge this please?

**Comment by gholliday** [comment]
@asranja @kmkumaran can you merge this please?

**Comment by azooinmyluggage** [comment]
We have already moved the script to vsts-rm-extensions repo https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskModules/powershell/Azure/SPNCreation.ps1

**Comment by azooinmyluggage** [comment]
We have already moved the script to vsts-rm-extensions repo https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskModules/powershell/Azure/SPNCreation.ps1

**Pull request merged**
